name: WORKFLOW-CALLER
on:
  workflow_dispatch:

jobs:
  JOB-CALL-WOKFLOW:
    strategy:
      matrix:
        python_version: [3.12, 3.9, 2,.7]
    uses: Rony-dot/actions_in_action/.github/workflows/unit_test.yml@main
    with:
      environment: 'dev'
      python_version: ${{ matrix.python_version }}
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
