name: WORKFLOW-CALLER
on:
  workflow_dispatch:

jobs:
  JOB-CALL-WOKFLOW:
    uses: Rony-dot/actions_in_action/.github/workflows/unit_test.yml@main
    with:
      environment: 'dev'
      PYTHON_VERSION: 3.12
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
