name: WORKFLOW-CALLER
on:
  workflow_dispatch:
  push:

jobs:
  JOB-CALL-WOKFLOW:
    uses: Rony-dot/actions_in_action/.github/workflows/unit_test.yml@main
    strategy:
      matrix:
        python_version: [3.12, 3.9, 3.8]
    with:
      environment: 'dev'
      python_version: ${{ matrix.python_version }}
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
